In [3]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('Mission.csv')

In [6]:
print(df)

   Mission_ID       Mission_Name       Agency       Country  Launch_Year  \
0       SM001      Chandrayaan-1         ISRO         India         2008
1       SM002      Chandrayaan-2         ISRO         India         2019
2       SM003         Mangalyaan         ISRO         India         2013
3       SM004          Aditya-L1         ISRO         India         2023
4       SM005            GSAT-11         ISRO         India         2018
5       SM006           INSAT-3D         ISRO         India         2013
6       SM007                NaN         ISRO         India         2011
7       SM008         Cartosat-2         ISRO         India         2007
8       SM009          Apollo 11         NASA           USA         1969
9       SM010          Apollo 13         NASA           USA         1970
10      SM011         James Webb         NASA           USA         2021
11      SM012          Artemis I         NASA           USA         2022
12      SM013             Hubble         NASA           USA         1990
13      SM014                NaN         NASA           USA         1999
14      SM015         Starlink-1       SpaceX           USA         2019
15      SM016         Starlink-2       SpaceX           USA         2020
16      SM017              CRS-7       SpaceX           USA         2015
17      SM018      Dragon Demo-2       SpaceX           USA         2020
18      SM019  Falcon Heavy Test       SpaceX           USA         2018
19      SM020                NaN       SpaceX           USA         2021
20      SM021         Tiangong-1         CNSA         China         2011
21      SM022          Chang'e-3         CNSA         China         2013
22      SM023          Chang'e-5         CNSA         China         2020
23      SM024                NaN         CNSA         China         2017
24      SM025          Tianwen-1         CNSA         China         2020
25      SM026            Mars 96    Roscosmos        Russia         1996
26      SM027            Luna 25    Roscosmos        Russia         2023
27      SM028          GLONASS-K    Roscosmos        Russia         2018
28      SM029                NaN    Roscosmos        Russia         2014
29      SM030           Vostok 1    Roscosmos        Russia         1961
30      SM031     Ariane 5 VA241          ESA        Europe         2018
31      SM032        Sentinel-1A          ESA        Europe         2014
32      SM033               Gaia          ESA        Europe         2013
33      SM034                NaN          ESA        Europe         2002
34      SM035            ExoMars          ESA        Europe         2016
35      SM036        BepiColombo          ESA        Europe         2018
36      SM037           Hayabusa         JAXA         Japan         2003
37      SM038          Hayabusa2         JAXA         Japan         2014
38      SM039                NaN         JAXA         Japan         2011
39      SM040           Akatsuki         JAXA         Japan         2010
40      SM041         Arabsat-6A       SpaceX  Saudi Arabia         2019
41      SM042                NaN  Blue Origin           USA         2021
42      SM043  New Shepard NS-16  Blue Origin           USA         2021
43      SM044          Vega VV17          ESA        Europe         2020
44      SM045           PSLV-C37         ISRO         India         2017
45      SM046           PSLV-C44         ISRO         India         2019
46      SM047                NaN         ISRO         India         2004
47      SM048     Gaganyaan Test         ISRO         India         2023
48      SM049                NaN         NASA           USA         2003
49      SM050             Kepler         NASA           USA         2009
50      SM051               Lucy         NASA           USA         2021
51      SM052                NaN         NASA           USA         2012
52      SM053               TESS         NASA           USA         2018
53      SM054         OSIRIS-REx         NASA           USA         2016
54      SM055                NaN          ESA        Europe         2010
55      SM056       Iridium NEXT       SpaceX           USA         2019
56      SM057                NaN       SpaceX           USA         2016
57      SM058           OneWeb-1       OneWeb            UK         2019
58      SM059           OneWeb-2       OneWeb            UK         2020
59      SM060                NaN      Private           USA         2022

       Launch_Site         Rocket Payload_kg     Mission_Type  \
0      Sriharikota           PSLV       1380            Lunar
1      Sriharikota    GSLV Mk III       3850            Lunar
2      Sriharikota           PSLV       1350     Mars Orbiter
3      Sriharikota           PSLV       1480            Solar
4           Kourou       Ariane 5       5854    Communication
5      Sriharikota           PSLV       2060          Weather
6      Sriharikota           PSLV        NaN        Earth Obs
7      Sriharikota           PSLV        680        Earth Obs
8          Kennedy       Saturn V      43000            Lunar
9          Kennedy       Saturn V      43000            Lunar
10          Kourou       Ariane 5       6200  Space Telescope
11         Kennedy            SLS      26000       Lunar Test
12         Kennedy            STS      11110        Telescope
13      Vandenberg       Delta II        950        Earth Obs
14  Cape Canaveral       Falcon 9      15600        Satellite
15  Cape Canaveral       Falcon 9      15600        Satellite
16  Cape Canaveral       Falcon 9       1950         Resupply
17         Kennedy       Falcon 9      12000           Crewed
18         Kennedy   Falcon Heavy        NaN             Test
19  Cape Canaveral       Falcon 9      16000        Satellite
20         Jiuquan  Long March 2F       8500    Space Station
21         Xichang  Long March 3B       3780            Lunar
22        Wenchang   Long March 5       8200            Lunar
23         Jiuquan  Long March 4C       1200        Earth Obs
24        Wenchang   Long March 5       5000             Mars
25        Baikonur       Proton-K       6180             Mars
26        Baikonur        Soyuz 2      Lunar            Lunar
27        Plesetsk          Soyuz        935       Navigation
28        Baikonur       Proton-M       6000    Communication
29        Baikonur       Vostok-K       4725           Crewed
30          Kourou       Ariane 5      10000    Communication
31          Kourou          Soyuz       2300        Earth Obs
32          Kourou          Soyuz       2030       Astrometry
33        Baikonur          Soyuz        NaN          Science
34        Baikonur       Proton-M       4300             Mars
35          Kourou       Ariane 5       4100          Mercury
36       Kagoshima            M-V        510         Asteroid
37     Tanegashima          H-IIA        609         Asteroid
38     Tanegashima          H-IIA        NaN        Earth Obs
39     Tanegashima          H-IIA        500            Venus
40         Kennedy   Falcon Heavy       6465    Communication
41           Texas    New Shepard        NaN       Suborbital
42           Texas    New Shepard        NaN           Crewed
43          Kourou           Vega       1200        Earth Obs
44     Sriharikota           PSLV       1378        Satellite
45     Sriharikota           PSLV        740         Military
46     Sriharikota           PSLV        NaN     Experimental
47     Sriharikota           LVM3        NaN      Crewed Test
48         Kennedy            STS      11110           Crewed
49  Cape Canaveral       Delta II       1052        Exoplanet
50  Cape Canaveral        Atlas V       1550         Asteroid
51      Vandenberg        Atlas V        NaN              Spy
52  Cape Canaveral       Falcon 9        362        Exoplanet
53  Cape Canaveral        Atlas V       2110         Asteroid
54          Kourou       Ariane 5       6500    Communication
55      Vandenberg       Falcon 9       9600    Communication
56  Cape Canaveral       Falcon 9        NaN             Test
57        Baikonur          Soyuz       6000        Satellite
58        Baikonur          Soyuz       6000        Satellite
59  Cape Canaveral       Falcon 9        NaN       Commercial

     Mission_Status  Mission_Cost_MUSD         Orbit
0           Success               83.0   Lunar Orbit
1   Partial Success              140.0   Trans Lunar
2           Success               74.0  Heliocentric
3           Success               46.0      L1 Orbit
4           Success              400.0           GEO
5           Success              250.0           GEO
6           Success              120.0           LEO
7           Success                NaN           LEO
8           Success             3550.0   Lunar Orbit
9           Failure             3500.0   Lunar Orbit
10          Success            10000.0      L2 Orbit
11          Success             4000.0   Lunar Orbit
12          Success             2500.0           LEO
13          Failure              180.0           LEO
14          Success               50.0           LEO
15          Success               52.0           LEO
16          Failure               60.0           LEO
17          Success               90.0           LEO
18          Success                NaN  Heliocentric
19          Success               55.0           LEO
20          Success             1000.0           LEO
21          Success             1200.0   Lunar Orbit
22          Success             1500.0   Lunar Orbit
23          Failure                NaN           LEO
24          Success             2000.0  Heliocentric
25          Failure              300.0           NaN
26          Failure              200.0   Lunar Orbit
27          Success              180.0           LEO
28          Failure                NaN           GEO
29          Success              100.0           LEO
30          Success              200.0           GEO
31          Success              280.0           LEO
32          Success              740.0      L2 Orbit
33          Failure                NaN           LEO
34  Partial Success             1400.0  Heliocentric
35          Success             2000.0  Heliocentric
36          Success              150.0  Heliocentric
37          Success              300.0  Heliocentric
38          Success                NaN           LEO
39  Partial Success              300.0  Heliocentric
40          Success               90.0           GEO
41          Success                NaN    Suborbital
42          Success               28.0    Suborbital
43          Failure              180.0           LEO
44          Success               15.0           LEO
45  Partial Success               25.0           LEO
46          Failure                NaN           LEO
47          Success              300.0           LEO
48          Failure             2000.0           LEO
49          Success              600.0  Heliocentric
50          Success              980.0  Heliocentric
51          Success                NaN           LEO
52          Success              337.0           HEO
53          Success              800.0  Heliocentric
54          Success                NaN           GEO
55          Success               70.0           LEO
56          Failure                NaN           LEO
57          Success              100.0           LEO
58          Failure              110.0           LEO
59          Success                NaN           LEO

In [7]:
display(df)

,Mission_ID,Mission_Name,Agency,Country,Launch_Year,Launch_Site,Rocket,Payload_kg,Mission_Type,Mission_Status,Mission_Cost_MUSD,Orbit
0,SM001,Chandrayaan-1,ISRO,India,2008,Sriharikota,PSLV,1380,Lunar,Success,83.0,Lunar Orbit
1,SM002,Chandrayaan-2,ISRO,India,2019,Sriharikota,GSLV Mk III,3850,Lunar,Partial Success,140.0,Trans Lunar
2,SM003,Mangalyaan,ISRO,India,2013,Sriharikota,PSLV,1350,Mars Orbiter,Success,74.0,Heliocentric
3,SM004,Aditya-L1,ISRO,India,2023,Sriharikota,PSLV,1480,Solar,Success,46.0,L1 Orbit
4,SM005,GSAT-11,ISRO,India,2018,Kourou,Ariane 5,5854,Communication,Success,400.0,GEO
5,SM006,INSAT-3D,ISRO,India,2013,Sriharikota,PSLV,2060,Weather,Success,250.0,GEO
6,SM007,NaN,ISRO,India,2011,Sriharikota,PSLV,NaN,Earth Obs,Success,120.0,LEO
7,SM008,Cartosat-2,ISRO,India,2007,Sriharikota,PSLV,680,Earth Obs,Success,NaN,LEO
8,SM009,Apollo 11,NASA,USA,1969,Kennedy,Saturn V,43000,Lunar,Success,3550.0,Lunar Orbit
9,SM010,Apollo 13,NASA,USA,1970,Kennedy,Saturn V,43000,Lunar,Failure,3500.0,Lunar Orbit
10,SM011,James Webb,NASA,USA,2021,Kourou,Ariane 5,6200,Space Telescope,Success,10000.0,L2 Orbit
11,SM012,Artemis I,NASA,USA,2022,Kennedy,SLS,26000,Lunar Test,Success,4000.0,Lunar Orbit
12,SM013,Hubble,NASA,USA,1990,Kennedy,STS,11110,Telescope,Success,2500.0,LEO
13,SM014,NaN,NASA,USA,1999,Vandenberg,Delta II,950,Earth Obs,Failure,180.0,LEO
14,SM015,Starlink-1,SpaceX,USA,2019,Cape Canaveral,Falcon 9,15600,Satellite,Success,50.0,LEO
15,SM016,Starlink-2,SpaceX,USA,2020,Cape Canaveral,Falcon 9,15600,Satellite,Success,52.0,LEO
16,SM017,CRS-7,SpaceX,USA,2015,Cape Canaveral,Falcon 9,1950,Resupply,Failure,60.0,LEO
17,SM018,Dragon Demo-2,SpaceX,USA,2020,Kennedy,Falcon 9,12000,Crewed,Success,90.0,LEO
18,SM019,Falcon Heavy Test,SpaceX,USA,2018,Kennedy,Falcon Heavy,NaN,Test,Success,NaN,Heliocentric
19,SM020,NaN,SpaceX,USA,2021,Cape Canaveral,Falcon 9,16000,Satellite,Success,55.0,LEO
20,SM021,Tiangong-1,CNSA,China,2011,Jiuquan,Long March 2F,8500,Space Station,Success,1000.0,LEO
21,SM022,Chang'e-3,CNSA,China,2013,Xichang,Long March 3B,3780,Lunar,Success,1200.0,Lunar Orbit
22,SM023,Chang'e-5,CNSA,China,2020,Wenchang,Long March 5,8200,Lunar,Success,1500.0,Lunar Orbit
23,SM024,NaN,CNSA,China,2017,Jiuquan,Long March 4C,1200,Earth Obs,Failure,NaN,LEO
24,SM025,Tianwen-1,CNSA,China,2020,Wenchang,Long March 5,5000,Mars,Success,2000.0,Heliocentric
25,SM026,Mars 96,Roscosmos,Russia,1996,Baikonur,Proton-K,6180,Mars,Failure,300.0,NaN
26,SM027,Luna 25,Roscosmos,Russia,2023,Baikonur,Soyuz 2,Lunar,Lunar,Failure,200.0,Lunar Orbit
27,SM028,GLONASS-K,Roscosmos,Russia,2018,Plesetsk,Soyuz,935,Navigation,Success,180.0,LEO
28,SM029,NaN,Roscosmos,Russia,2014,Baikonur,Proton-M,6000,Communication,Failure,NaN,GEO
29,SM030,Vostok 1,Roscosmos,Russia,1961,Baikonur,Vostok-K,4725,Crewed,Success,100.0,LEO
30,SM031,Ariane 5 VA241,ESA,Europe,2018,Kourou,Ariane 5,10000,Communication,Success,200.0,GEO
31,SM032,Sentinel-1A,ESA,Europe,2014,Kourou,Soyuz,2300,Earth Obs,Success,280.0,LEO
32,SM033,Gaia,ESA,Europe,2013,Kourou,Soyuz,2030,Astrometry,Success,740.0,L2 Orbit
33,SM034,NaN,ESA,Europe,2002,Baikonur,Soyuz,NaN,Science,Failure,NaN,LEO
34,SM035,ExoMars,ESA,Europe,2016,Baikonur,Proton-M,4300,Mars,Partial Success,1400.0,Heliocentric
35,SM036,BepiColombo,ESA,Europe,2018,Kourou,Ariane 5,4100,Mercury,Success,2000.0,Heliocentric
36,SM037,Hayabusa,JAXA,Japan,2003,Kagoshima,M-V,510,Asteroid,Success,150.0,Heliocentric
37,SM038,Hayabusa2,JAXA,Japan,2014,Tanegashima,H-IIA,609,Asteroid,Success,300.0,Heliocentric
38,SM039,NaN,JAXA,Japan,2011,Tanegashima,H-IIA,NaN,Earth Obs,Success,NaN,LEO
39,SM040,Akatsuki,JAXA,Japan,2010,Tanegashima,H-IIA,500,Venus,Partial Success,300.0,Heliocentric
40,SM041,Arabsat-6A,SpaceX,Saudi Arabia,2019,Kennedy,Falcon Heavy,6465,Communication,Success,90.0,GEO
41,SM042,NaN,Blue Origin,USA,2021,Texas,New Shepard,NaN,Suborbital,Success,NaN,Suborbital
42,SM043,New Shepard NS-16,Blue Origin,USA,2021,Texas,New Shepard,NaN,Crewed,Success,28.0,Suborbital
43,SM044,Vega VV17,ESA,Europe,2020,Kourou,Vega,1200,Earth Obs,Failure,180.0,LEO
44,SM045,PSLV-C37,ISRO,India,2017,Sriharikota,PSLV,1378,Satellite,Success,15.0,LEO
45,SM046,PSLV-C44,ISRO,India,2019,Sriharikota,PSLV,740,Military,Partial Success,25.0,LEO
46,SM047,NaN,ISRO,India,2004,Sriharikota,PSLV,NaN,Experimental,Failure,NaN,LEO
47,SM048,Gaganyaan Test,ISRO,India,2023,Sriharikota,LVM3,NaN,Crewed Test,Success,300.0,LEO
48,SM049,NaN,NASA,USA,2003,Kennedy,STS,11110,Crewed,Failure,2000.0,LEO
49,SM050,Kepler,NASA,USA,2009,Cape Canaveral,Delta II,1052,Exoplanet,Success,600.0,Heliocentric
50,SM051,Lucy,NASA,USA,2021,Cape Canaveral,Atlas V,1550,Asteroid,Success,980.0,Heliocentric
51,SM052,NaN,NASA,USA,2012,Vandenberg,Atlas V,NaN,Spy,Success,NaN,LEO
52,SM053,TESS,NASA,USA,2018,Cape Canaveral,Falcon 9,362,Exoplanet,Success,337.0,HEO
53,SM054,OSIRIS-REx,NASA,USA,2016,Cape Canaveral,Atlas V,2110,Asteroid,Success,800.0,Heliocentric
54,SM055,NaN,ESA,Europe,2010,Kourou,Ariane 5,6500,Communication,Success,NaN,GEO
55,SM056,Iridium NEXT,SpaceX,USA,2019,Vandenberg,Falcon 9,9600,Communication,Success,70.0,LEO
56,SM057,NaN,SpaceX,USA,2016,Cape Canaveral,Falcon 9,NaN,Test,Failure,NaN,LEO
57,SM058,OneWeb-1,OneWeb,UK,2019,Baikonur,Soyuz,6000,Satellite,Success,100.0,LEO
58,SM059,OneWeb-2,OneWeb,UK,2020,Baikonur,Soyuz,6000,Satellite,Failure,110.0,LEO
59,SM060,NaN,Private,USA,2022,Cape Canaveral,Falcon 9,NaN,Commercial,Success,NaN,LEO

In [8]:
df.head(5)

,Mission_ID,Mission_Name,Agency,Country,Launch_Year,Launch_Site,Rocket,Payload_kg,Mission_Type,Mission_Status,Mission_Cost_MUSD,Orbit
0,SM001,Chandrayaan-1,ISRO,India,2008,Sriharikota,PSLV,1380,Lunar,Success,83.0,Lunar Orbit
1,SM002,Chandrayaan-2,ISRO,India,2019,Sriharikota,GSLV Mk III,3850,Lunar,Partial Success,140.0,Trans Lunar
2,SM003,Mangalyaan,ISRO,India,2013,Sriharikota,PSLV,1350,Mars Orbiter,Success,74.0,Heliocentric
3,SM004,Aditya-L1,ISRO,India,2023,Sriharikota,PSLV,1480,Solar,Success,46.0,L1 Orbit
4,SM005,GSAT-11,ISRO,India,2018,Kourou,Ariane 5,5854,Communication,Success,400.0,GEO

In [9]:
df.tail(5)

,Mission_ID,Mission_Name,Agency,Country,Launch_Year,Launch_Site,Rocket,Payload_kg,Mission_Type,Mission_Status,Mission_Cost_MUSD,Orbit
55,SM056,Iridium NEXT,SpaceX,USA,2019,Vandenberg,Falcon 9,9600,Communication,Success,70.0,LEO
56,SM057,NaN,SpaceX,USA,2016,Cape Canaveral,Falcon 9,NaN,Test,Failure,NaN,LEO
57,SM058,OneWeb-1,OneWeb,UK,2019,Baikonur,Soyuz,6000,Satellite,Success,100.0,LEO
58,SM059,OneWeb-2,OneWeb,UK,2020,Baikonur,Soyuz,6000,Satellite,Failure,110.0,LEO
59,SM060,NaN,Private,USA,2022,Cape Canaveral,Falcon 9,NaN,Commercial,Success,NaN,LEO

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Mission_ID         60 non-null     object
 1   Mission_Name       46 non-null     object
 2   Agency             60 non-null     object
 3   Country            60 non-null     object
 4   Launch_Year        60 non-null     int64
 5   Launch_Site        60 non-null     object
 6   Rocket             60 non-null     object
 7   Payload_kg         49 non-null     object
 8   Mission_Type       60 non-null     object
 9   Mission_Status     60 non-null     object
 10  Mission_Cost_MUSD  48 non-null     float64
 11  Orbit              59 non-null     object
dtypes: float64(1), int64(1), object(10)
memory usage: 5.8+ KB

In [11]:
df["Payload_kg"] = pd.to_numeric(df["Payload_kg"], errors="coerce").astype(float)
df["Mission_Cost_MUSD"] = pd.to_numeric(df["Mission_Cost_MUSD"], errors="coerce").astype(float)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Mission_ID         60 non-null     object
 1   Mission_Name       46 non-null     object
 2   Agency             60 non-null     object
 3   Country            60 non-null     object
 4   Launch_Year        60 non-null     int64
 5   Launch_Site        60 non-null     object
 6   Rocket             60 non-null     object
 7   Payload_kg         48 non-null     float64
 8   Mission_Type       60 non-null     object
 9   Mission_Status     60 non-null     object
 10  Mission_Cost_MUSD  48 non-null     float64
 11  Orbit              59 non-null     object
dtypes: float64(2), int64(1), object(9)
memory usage: 5.8+ KB

In [13]:
df['Agency']

0            ISRO
1            ISRO
2            ISRO
3            ISRO
4            ISRO
5            ISRO
6            ISRO
7            ISRO
8            NASA
9            NASA
10           NASA
11           NASA
12           NASA
13           NASA
14         SpaceX
15         SpaceX
16         SpaceX
17         SpaceX
18         SpaceX
19         SpaceX
20           CNSA
21           CNSA
22           CNSA
23           CNSA
24           CNSA
25      Roscosmos
26      Roscosmos
27      Roscosmos
28      Roscosmos
29      Roscosmos
30            ESA
31            ESA
32            ESA
33            ESA
34            ESA
35            ESA
36           JAXA
37           JAXA
38           JAXA
39           JAXA
40         SpaceX
41    Blue Origin
42    Blue Origin
43            ESA
44           ISRO
45           ISRO
46           ISRO
47           ISRO
48           NASA
49           NASA
50           NASA
51           NASA
52           NASA
53           NASA
54            ESA
55         SpaceX
56         SpaceX
57         OneWeb
58         OneWeb
59        Private
Name: Agency, dtype: object

In [14]:
print(df.isnull().sum())

Mission_ID            0
Mission_Name         14
Agency                0
Country               0
Launch_Year           0
Launch_Site           0
Rocket                0
Payload_kg           12
Mission_Type          0
Mission_Status        0
Mission_Cost_MUSD    12
Orbit                 1
dtype: int64

In [15]:
df.dtypes

Mission_ID            object
Mission_Name          object
Agency                object
Country               object
Launch_Year            int64
Launch_Site           object
Rocket                object
Payload_kg           float64
Mission_Type          object
Mission_Status        object
Mission_Cost_MUSD    float64
Orbit                 object
dtype: object

In [16]:
print(type(df['Payload_kg']))

<class 'pandas.core.series.Series'>

In [17]:
pd.pivot_table(df,
               values="Mission_Cost_MUSD",
               index="Agency",
               columns="Mission_Status",
               aggfunc="mean")

Mission_Status      Failure  Partial Success      Success
Agency
Blue Origin             NaN              NaN    28.000000
CNSA                    NaN              NaN  1425.000000
ESA              180.000000           1400.0   805.000000
ISRO                    NaN             82.5   161.000000
JAXA                    NaN            300.0   225.000000
NASA            1893.333333              NaN  2845.875000
OneWeb           110.000000              NaN   100.000000
Roscosmos        250.000000              NaN   140.000000
SpaceX            60.000000              NaN    67.833333

numpy operaations

In [18]:
import numpy as np

data = df[["Launch_Year", "Payload_kg", "Mission_Cost_MUSD"]].to_numpy()

launch_year = data[:, 0]
payload = data[:, 1]
cost = data[:, 2]

In [28]:

np.nanmean(cost)

np.float64(888.2291666666666)

In [20]:
np.nanmin(cost)

np.float64(15.0)

In [21]:
np.nanmax(cost)

np.float64(10000.0)

In [22]:
np.nansum(payload)

np.float64(331000.0)

In [23]:
np.nanstd(payload)

np.float64(9141.607114664734)

In [24]:
np.nanstd(cost)

np.float64(1655.0438216703828)

In [25]:
data[cost > 1000]

array([[ 1969., 43000.,  3550.],
       [ 1970., 43000.,  3500.],
       [ 2021.,  6200., 10000.],
       [ 2022., 26000.,  4000.],
       [ 1990., 11110.,  2500.],
       [ 2013.,  3780.,  1200.],
       [ 2020.,  8200.,  1500.],
       [ 2020.,  5000.,  2000.],
       [ 2016.,  4300.,  1400.],
       [ 2018.,  4100.,  2000.],
       [ 2003., 11110.,  2000.]])

In [26]:
data[np.argsort(payload)]

array([[2.018e+03, 3.620e+02, 3.370e+02],
       [2.010e+03, 5.000e+02, 3.000e+02],
       [2.003e+03, 5.100e+02, 1.500e+02],
       [2.014e+03, 6.090e+02, 3.000e+02],
       [2.007e+03, 6.800e+02,       nan],
       [2.019e+03, 7.400e+02, 2.500e+01],
       [2.018e+03, 9.350e+02, 1.800e+02],
       [1.999e+03, 9.500e+02, 1.800e+02],
       [2.009e+03, 1.052e+03, 6.000e+02],
       [2.017e+03, 1.200e+03,       nan],
       [2.020e+03, 1.200e+03, 1.800e+02],
       [2.013e+03, 1.350e+03, 7.400e+01],
       [2.017e+03, 1.378e+03, 1.500e+01],
       [2.008e+03, 1.380e+03, 8.300e+01],
       [2.023e+03, 1.480e+03, 4.600e+01],
       [2.021e+03, 1.550e+03, 9.800e+02],
       [2.015e+03, 1.950e+03, 6.000e+01],
       [2.013e+03, 2.030e+03, 7.400e+02],
       [2.013e+03, 2.060e+03, 2.500e+02],
       [2.016e+03, 2.110e+03, 8.000e+02],
       [2.014e+03, 2.300e+03, 2.800e+02],
       [2.013e+03, 3.780e+03, 1.200e+03],
       [2.019e+03, 3.850e+03, 1.400e+02],
       [2.018e+03, 4.100e+03, 2.000e+03],
       [2.016e+03, 4.300e+03, 1.400e+03],
       [1.961e+03, 4.725e+03, 1.000e+02],
       [2.020e+03, 5.000e+03, 2.000e+03],
       [2.018e+03, 5.854e+03, 4.000e+02],
       [2.014e+03, 6.000e+03,       nan],
       [2.020e+03, 6.000e+03, 1.100e+02],
       [2.019e+03, 6.000e+03, 1.000e+02],
       [1.996e+03, 6.180e+03, 3.000e+02],
       [2.021e+03, 6.200e+03, 1.000e+04],
       [2.019e+03, 6.465e+03, 9.000e+01],
       [2.010e+03, 6.500e+03,       nan],
       [2.020e+03, 8.200e+03, 1.500e+03],
       [2.011e+03, 8.500e+03, 1.000e+03],
       [2.019e+03, 9.600e+03, 7.000e+01],
       [2.018e+03, 1.000e+04, 2.000e+02],
       [1.990e+03, 1.111e+04, 2.500e+03],
       [2.003e+03, 1.111e+04, 2.000e+03],
       [2.020e+03, 1.200e+04, 9.000e+01],
       [2.019e+03, 1.560e+04, 5.000e+01],
       [2.020e+03, 1.560e+04, 5.200e+01],
       [2.021e+03, 1.600e+04, 5.500e+01],
       [2.022e+03, 2.600e+04, 4.000e+03],
       [1.969e+03, 4.300e+04, 3.550e+03],
       [1.970e+03, 4.300e+04, 3.500e+03],
       [2.011e+03,       nan, 1.200e+02],
       [2.016e+03,       nan,       nan],
       [2.023e+03,       nan, 2.000e+02],
       [2.021e+03,       nan, 2.800e+01],
       [2.023e+03,       nan, 3.000e+02],
       [2.004e+03,       nan,       nan],
       [2.021e+03,       nan,       nan],
       [2.011e+03,       nan,       nan],
       [2.018e+03,       nan,       nan],
       [2.002e+03,       nan,       nan],
       [2.012e+03,       nan,       nan],
       [2.022e+03,       nan,       nan]])